#!/usr/bin/env bash
# Phase 1 gate: perf.data
#
# We can't call `perf record` here (kernel.perf_event_paranoid=4 blocks
# unprivileged event opens), so the fixture is generated by the
# `make-perf` binary in scrump-test-fixtures. It produces a real
# PERF_MAGIC2 file with HEADER_CMDLINE carrying the planted tokens —
# `file(1)` identifies it as "Linux perf recording, version 2".
#
# Assertions:
#   1. scrump auto-detects the file as `perf`.
#   2. Scrub reports >=1 hit and rewrites in place.
#   3. File size preserved.
#   4. Magic "PERFILE2" is intact (post-scrub).
#   5. No planted token in raw bytes.

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

# Ensure fixture generator is built.
( cd "$ROOT" && cargo build -p scrump-test-fixtures --quiet 2>&1 ) || die "fixture build failed"
MAKE_PERF="$ROOT/target/debug/make-perf"
[[ -x "$MAKE_PERF" ]] || die "missing $MAKE_PERF"

GH=$(plant_token ghp)
HF=$(plant_token hf)
ANT=$(plant_token anthropic)
PD="$TMP/test.perf.data"

"$MAKE_PERF" "$PD" "perf" \
    "env GH_TOKEN=$GH HF_TOKEN=$HF ANTHROPIC_API_KEY=$ANT sleep 0.05" \
    >/dev/null

PRE_SIZE=$(stat -c%s "$PD")
info "phase1: $PD ($PRE_SIZE bytes)"

# Pre-scrub: tokens visible in raw bytes.
grep -aE 'ghp_|hf_|sk-ant-' "$PD" >/dev/null || die "phase1: planted tokens not in fixture?"

# 1. Format auto-detect.
assert_scrump_format "$PD" "perf"
ok "phase1: auto-detected as 'perf'"

# 2. Scrub.
SCRUB_OUT=$("$BIN" scrub "$PD" 2>&1)
echo "$SCRUB_OUT" | grep -q 'hits redacted' || die "phase1: scrub did not report any redactions:\n$SCRUB_OUT"
ok "phase1: scrub reported redactions"

# 3. File size preserved.
POST_SIZE=$(stat -c%s "$PD")
[[ "$PRE_SIZE" == "$POST_SIZE" ]] || die "phase1: size changed ($PRE_SIZE -> $POST_SIZE)"
ok "phase1: file size preserved"

# 4. Magic intact.
head -c 8 "$PD" | grep -q '^PERFILE2' || die "phase1: PERFILE2 magic broken"
ok "phase1: PERFILE2 magic intact"

# 5. No token leftover.
assert_clean_of_tokens "$PD"
ok "phase1: no planted token remains"

ok "phase1: GREEN"
