//! pcap / pcapng capture file handler.
//!
//! Covers two on-disk formats:
//!
//! * **classic pcap** (tcpdump's original format): 24-byte file header
//!   followed by per-packet records `{ ts_sec, ts_usec, captured_len,
//!   original_len, packet_bytes }`. Magic word `0xa1b2c3d4` (host order
//!   `µ`-sec) or `0xa1b23c4d` (nano-sec); byte-swapped variants
//!   `0xd4c3b2a1` / `0x4d3cb2a1` indicate the file was written on the
//!   opposite endian.
//!
//! * **pcapng** (the modern format generated by Wireshark and recent
//!   tcpdump): a sequence of Block Types; the only one we have to walk
//!   is `0x00000006` (Enhanced Packet Block). Each block ends with a
//!   redundant total-length field that we use to skip.
//!
//! For both we surface each packet's payload bytes (which is where
//! HTTP headers, Authorization tokens, query strings, etc. live) as a
//! [`Chunk`] with absolute file offset and origin
//! `Section("pcap.packet[N]")` / `Section("pcapng.epb[N]")`. Redaction
//! is byte-level zero-fill at those offsets — the surrounding link-level
//! and IP/TCP framing is untouched, so the file remains readable by
//! `tcpdump -r` and Wireshark, with only the token bytes blanked out.

use std::io::Read;
use std::path::Path;

use byteorder::{BigEndian, ByteOrder, LittleEndian};
use scrump_core::{
    apply_hits_in_place, Chunk, ChunkOrigin, Format, Handler, Hit, Result, ScrumpError,
};

// ---- magics ----------------------------------------------------------------

const PCAP_LE_USEC: u32 = 0xa1b2_c3d4;
const PCAP_LE_NSEC: u32 = 0xa1b2_3c4d;
const PCAP_BE_USEC: u32 = 0xd4c3_b2a1;
const PCAP_BE_NSEC: u32 = 0x4d3c_b2a1;

const PCAPNG_SHB: u32 = 0x0a0d_0d0a;
const PCAPNG_EPB: u32 = 0x0000_0006;
const PCAPNG_BOM_LE: u32 = 0x1a2b_3c4d;
const PCAPNG_BOM_BE: u32 = 0x4d3c_2b1a;

// ---- types -----------------------------------------------------------------

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Endian {
    Le,
    Be,
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Variant {
    Classic,
    Ng,
}

#[derive(Clone, Debug)]
struct Packet {
    /// Absolute file offset of the packet's payload bytes (after its
    /// per-record header).
    payload_offset: u64,
    payload_len: u64,
    /// Index inside the file (for labelling).
    index: usize,
}

pub struct PcapFile {
    bytes: Vec<u8>,
    variant: Variant,
    #[allow(dead_code)]
    endian: Endian,
    packets: Vec<Packet>,
}

impl PcapFile {
    pub fn open_path(path: &Path) -> Result<Self> {
        let mut f = std::fs::File::open(path)?;
        let mut bytes = Vec::new();
        f.read_to_end(&mut bytes)?;
        Self::from_bytes(bytes)
    }

    pub fn from_bytes(bytes: Vec<u8>) -> Result<Self> {
        if bytes.len() < 24 {
            return Err(ScrumpError::InvalidFile(
                "pcap: file shorter than 24-byte header".into(),
            ));
        }
        // Classic pcap?
        let m_le = LittleEndian::read_u32(&bytes[..4]);
        let m_be = BigEndian::read_u32(&bytes[..4]);
        if m_le == PCAP_LE_USEC || m_le == PCAP_LE_NSEC {
            let packets = parse_classic(&bytes, Endian::Le)?;
            return Ok(Self {
                bytes,
                variant: Variant::Classic,
                endian: Endian::Le,
                packets,
            });
        }
        if m_le == PCAP_BE_USEC || m_le == PCAP_BE_NSEC {
            let packets = parse_classic(&bytes, Endian::Be)?;
            return Ok(Self {
                bytes,
                variant: Variant::Classic,
                endian: Endian::Be,
                packets,
            });
        }
        // pcapng?
        if m_le == PCAPNG_SHB || m_be == PCAPNG_SHB {
            let endian = detect_pcapng_endian(&bytes)?;
            let packets = parse_pcapng(&bytes, endian)?;
            return Ok(Self {
                bytes,
                variant: Variant::Ng,
                endian,
                packets,
            });
        }
        Err(ScrumpError::InvalidFile(
            "pcap: not pcap or pcapng (unknown magic)".into(),
        ))
    }
}

fn detect_pcapng_endian(bytes: &[u8]) -> Result<Endian> {
    if bytes.len() < 12 {
        return Err(ScrumpError::InvalidFile(
            "pcapng: file shorter than 12 bytes".into(),
        ));
    }
    // Section Header Block carries a 4-byte byte-order magic at offset 8.
    let bom_le = LittleEndian::read_u32(&bytes[8..12]);
    if bom_le == PCAPNG_BOM_LE {
        return Ok(Endian::Le);
    }
    if bom_le == PCAPNG_BOM_BE {
        return Ok(Endian::Be);
    }
    Err(ScrumpError::InvalidFile(
        "pcapng: missing byte-order magic in SHB".into(),
    ))
}

fn read_u32(b: &[u8], e: Endian) -> u32 {
    match e {
        Endian::Le => LittleEndian::read_u32(b),
        Endian::Be => BigEndian::read_u32(b),
    }
}

fn parse_classic(bytes: &[u8], e: Endian) -> Result<Vec<Packet>> {
    let mut packets = Vec::new();
    let mut cursor = 24u64;
    let mut idx = 0usize;
    while (cursor as usize) + 16 <= bytes.len() {
        let off = cursor as usize;
        // Record header: ts_sec(4) ts_usec(4) captured_len(4) original_len(4)
        let captured = read_u32(&bytes[off + 8..off + 12], e) as u64;
        let payload_off = cursor + 16;
        let payload_end = payload_off + captured;
        if (payload_end as usize) > bytes.len() {
            // Truncated final record — stop here gracefully.
            break;
        }
        packets.push(Packet {
            payload_offset: payload_off,
            payload_len: captured,
            index: idx,
        });
        cursor = payload_end;
        idx += 1;
    }
    Ok(packets)
}

fn parse_pcapng(bytes: &[u8], e: Endian) -> Result<Vec<Packet>> {
    let mut packets = Vec::new();
    let mut cursor = 0u64;
    let mut idx = 0usize;
    while (cursor as usize) + 8 <= bytes.len() {
        let off = cursor as usize;
        let block_type = read_u32(&bytes[off..off + 4], e);
        let block_total = read_u32(&bytes[off + 4..off + 8], e) as u64;
        if block_total < 12 || (cursor + block_total) as usize > bytes.len() {
            // Malformed; stop.
            break;
        }
        if block_type == PCAPNG_EPB {
            // Enhanced Packet Block body layout (after the 8-byte block
            // header):
            //   interface_id (4) ts_high (4) ts_low (4) cap_len (4)
            //   orig_len (4) packet_data (cap_len bytes, padded to 4)
            //   options …  trailing block_total (4)
            if block_total < 32 {
                cursor += block_total;
                continue;
            }
            let cap_len = read_u32(&bytes[off + 20..off + 24], e) as u64;
            let payload_off = cursor + 28;
            let payload_end = payload_off + cap_len;
            if (payload_end as usize) <= bytes.len() {
                packets.push(Packet {
                    payload_offset: payload_off,
                    payload_len: cap_len,
                    index: idx,
                });
                idx += 1;
            }
        }
        cursor += block_total;
    }
    Ok(packets)
}

// ---- Format impl -----------------------------------------------------------

impl Format for PcapFile {
    fn name(&self) -> &'static str {
        "pcap"
    }

    fn chunks<'a>(&'a self) -> Box<dyn Iterator<Item = Chunk<'a>> + 'a> {
        let label = match self.variant {
            Variant::Classic => "pcap.packet",
            Variant::Ng => "pcapng.epb",
        };
        let chunks: Vec<Chunk<'a>> = self
            .packets
            .iter()
            .filter_map(|p| {
                let from = p.payload_offset as usize;
                let to = from + p.payload_len as usize;
                if to > self.bytes.len() || p.payload_len == 0 {
                    return None;
                }
                Some(Chunk {
                    bytes: &self.bytes[from..to],
                    offset: p.payload_offset,
                    origin: ChunkOrigin::Section(format!("{label}[{}]", p.index)),
                })
            })
            .collect();
        Box::new(chunks.into_iter())
    }

    fn apply(&mut self, hits: &[Hit]) -> Result<()> {
        // Guard: every hit must land entirely inside a packet payload —
        // header bytes (record framing, block headers, byte-order magic)
        // are never to be touched.
        for h in hits {
            let inside = self.packets.iter().any(|p| {
                h.offset >= p.payload_offset
                    && (h.offset + h.len as u64) <= (p.payload_offset + p.payload_len)
            });
            if !inside {
                return Err(ScrumpError::RedactionFailed(format!(
                    "pcap: hit at offset {} (len {}) outside any packet payload — \
                     would corrupt framing",
                    h.offset, h.len
                )));
            }
        }
        apply_hits_in_place(&mut self.bytes, hits)
    }

    fn to_bytes(&self) -> Result<Vec<u8>> {
        Ok(self.bytes.clone())
    }
}

// ---- handler registration --------------------------------------------------

fn detect(head: &[u8], path: &Path) -> bool {
    if head.len() < 4 {
        return false;
    }
    let m = LittleEndian::read_u32(&head[..4]);
    if matches!(
        m,
        PCAP_LE_USEC | PCAP_LE_NSEC | PCAP_BE_USEC | PCAP_BE_NSEC | PCAPNG_SHB
    ) {
        return true;
    }
    let m_be = BigEndian::read_u32(&head[..4]);
    if m_be == PCAPNG_SHB {
        return true;
    }
    // Extension hint.
    let s = path.to_string_lossy();
    s.ends_with(".pcap") || s.ends_with(".pcapng") || s.ends_with(".cap")
}

fn open_path(path: &Path) -> Result<Box<dyn Format>> {
    Ok(Box::new(PcapFile::open_path(path)?))
}

fn open_bytes(bytes: Vec<u8>, _hint: Option<&Path>) -> Result<Box<dyn Format>> {
    Ok(Box::new(PcapFile::from_bytes(bytes)?))
}

pub fn handler() -> Handler {
    Handler {
        name: "pcap",
        detect,
        open_path,
        open_bytes,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Build a tiny one-packet classic pcap LE.
    fn synth_pcap(payload: &[u8]) -> Vec<u8> {
        use byteorder::WriteBytesExt;
        let mut f = Vec::new();
        // File header (24 bytes).
        f.write_u32::<LittleEndian>(PCAP_LE_USEC).unwrap();
        f.write_u16::<LittleEndian>(2).unwrap(); // major
        f.write_u16::<LittleEndian>(4).unwrap(); // minor
        f.write_i32::<LittleEndian>(0).unwrap(); // thiszone
        f.write_u32::<LittleEndian>(0).unwrap(); // sigfigs
        f.write_u32::<LittleEndian>(65535).unwrap(); // snaplen
        f.write_u32::<LittleEndian>(1).unwrap(); // network = LINKTYPE_ETHERNET
                                                 // Packet record header.
        f.write_u32::<LittleEndian>(0).unwrap(); // ts_sec
        f.write_u32::<LittleEndian>(0).unwrap(); // ts_usec
        f.write_u32::<LittleEndian>(payload.len() as u32).unwrap(); // captured_len
        f.write_u32::<LittleEndian>(payload.len() as u32).unwrap(); // original_len
        f.extend_from_slice(payload);
        f
    }

    #[test]
    fn detect_classic_pcap() {
        let f = synth_pcap(b"hello");
        assert!(detect(&f[..8], Path::new("/x/y.pcap")));
        assert!(!detect(b"nope", Path::new("/x/y")));
    }

    #[test]
    fn parses_classic_and_yields_payload_chunk() {
        let payload = b"GET / HTTP/1.1\r\nAuthorization: Bearer ghp_ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ab\r\n\r\n";
        let f = synth_pcap(payload);
        let pf = PcapFile::from_bytes(f).unwrap();
        assert_eq!(pf.packets.len(), 1);
        assert_eq!(pf.packets[0].payload_len, payload.len() as u64);
        let chunks: Vec<_> = pf.chunks().collect();
        assert_eq!(chunks.len(), 1);
        assert_eq!(chunks[0].bytes, payload);
        assert!(matches!(&chunks[0].origin, ChunkOrigin::Section(s) if s == "pcap.packet[0]"));
    }

    #[test]
    fn redacts_in_place_and_preserves_size() {
        let token = b"ghp_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
        let payload = [
            b"GET / HTTP/1.1\r\nAuthorization: Bearer " as &[u8],
            token,
            b"\r\n\r\n",
        ]
        .concat();
        let f = synth_pcap(&payload);
        let pre_len = f.len();
        let mut pf = PcapFile::from_bytes(f).unwrap();
        let pos = pf
            .bytes
            .windows(token.len())
            .position(|w| w == token)
            .unwrap() as u64;
        pf.apply(&[Hit {
            offset: pos,
            len: token.len(),
            rule_id: "test".into(),
            verified: None,
            replacement: scrump_core::Replacement::ZeroFill,
            origin: ChunkOrigin::Section("pcap.packet[0]".into()),
        }])
        .unwrap();
        let out = pf.to_bytes().unwrap();
        assert_eq!(out.len(), pre_len);
        assert!(!out.windows(token.len()).any(|w| w == token));
        // pcap magic still intact.
        assert_eq!(LittleEndian::read_u32(&out[..4]), PCAP_LE_USEC);
    }

    #[test]
    fn refuses_to_redact_outside_payload() {
        let f = synth_pcap(b"hello");
        let mut pf = PcapFile::from_bytes(f).unwrap();
        let err = pf
            .apply(&[Hit {
                offset: 0,
                len: 4,
                rule_id: "x".into(),
                verified: None,
                replacement: scrump_core::Replacement::ZeroFill,
                origin: ChunkOrigin::Section("evil".into()),
            }])
            .unwrap_err();
        assert!(matches!(err, ScrumpError::RedactionFailed(_)));
    }
}
